
spring.main.web-application-type=none

spring.task.scheduling.pool.size=0

spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration,\
  org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchClientAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchRepositoriesAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.elasticsearch.ReactiveElasticsearchRepositoriesAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.elasticsearch.ReactiveElasticsearchRestClientAutoConfiguration

app.search.elasticsearch.enabled=false

spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework=WARN
logging.level.com.taivs.EcommerceWeb=INFO
logging.level.org.hibernate=WARN
